#!/usr/bin/env python3

# standard imports
import argparse
import os
import sys
import time

# Set path to import local modules
sys.path = [os.path.join(os.path.dirname(__file__), "python")] + sys.path


def _parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "-l", "--local-subtensor",
        help="Use the specified local subtensor (i.e. la, cali, titan, etc.). "
             "When not specified, use the 'finney' network subtensor."
    )

    parser.add_argument(
        "-s", "--subnets",
        nargs="+",
        type=int,
        help="When specified, the list of netuids are checked. When not "
             "specified, all subnets are checked."
    )

    parser.add_argument(
        "-p", "--pending",
        action="store_true",
        help="When specified, print data for pending CHK hotkeys."
    )

    parser.add_argument(
        "-k", "--hotkey",
        help="Specify a different hotkey to check than Rizzo."
    )

    parser.add_argument(
        "-n", "--vali-name",
        default="Rizzo",
        help="Specify a different validator name in the table printout."
    )

    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Print verbose output."
    )

    return parser.parse_args()


def main(options):
    if options.verbose:
        bittensor.logging.enable_info()

    network = utils.get_subtensor_network(options.local_subtensor)
    netuids = options.subnets or utils.get_all_subnets(network)
    # sort_subnets = not bool(options.subnets)

    start_time = time.time()
    validator_data = SubnetDataMain(
        netuids, network, other_chk_hotkey=options.hotkey
    ).validator_data
    subnet_data_printer = SubnetDataPrinter(
        validator_data, netuids, options.pending, options.vali_name,
    )
    total_time = round(time.time() - start_time)

    subnet_data_printer.print_validator_data()
    print(f"\nSubnet data gathering took {utils.get_formatted_time(total_time)}.\n")


if __name__ == "__main__":
    try:
        options = _parse_args()

        # Import bittensor and local modules after parsing args to keep the
        # bittensor module from overriding the --help arg.
        import bittensor
        from subnet_data_main import SubnetDataMain
        from subnet_printer_chk import SubnetDataPrinter
        import utils

        main(options)

    except KeyboardInterrupt as exc:
        import traceback
        exc_list = traceback.format_exception_only(exc)
        exc_text = "\n" + "".join(exc_list).strip("\n")
        print(exc_text)
