#!/usr/bin/env python3

# standard imports
import argparse
import os
import sys
import time

# Add local validator_checker module path
sys.path = [os.path.dirname(__file__)] + sys.path


def _parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "-l", "--local-subtensor",
        dest="local_lite_subtensor",
        default=False,
        help="Use the specified local subtensor (i.e. la, cali, titan, etc.). "
             "When not specified, use the 'finney' network subtensor."
    )

    parser.add_argument(
        "-s", "--subnets",
        dest="netuids",
        nargs="+",
        type=int,
        help="When specified, the list of netuids are checked. When not "
             "specified, all subnets are checked."
    )

    parser.add_argument(
        "-p", "--pending",
        action="store_true",
        help="When specified, print data for pending CHK hotkeys."
    )

    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Print verbose output."
    )

    return parser.parse_args()


def main(options):
    if options.verbose:
        bittensor.logging.enable_info()

    network = get_lite_subtensor_network(options.local_lite_subtensor)

    start_time = time.time()
    subnet_data = SubnetDataMain(network, netuids=options.netuids)
    subnet_data_printer = SubnetDataPrinter(
        subnet_data.validator_data, subnet_data.netuids, options.pending,
    )
    total_time = round(time.time() - start_time)

    subnet_data_printer.print_validator_data()
    print(f"\nSubnet data gathering took {get_formatted_time(total_time)}.\n")


if __name__ == "__main__":
    try:
        options = _parse_args()

        # Import bittensor and local modules after parsing args to keep the
        # bittensor module from overriding the --help arg.
        import bittensor
        from validator_checker.subnet_data_main import SubnetDataMain
        from validator_checker.subnet_printer_chk import SubnetDataPrinter
        from validator_checker.utils import (
            get_formatted_time,
            get_lite_subtensor_network,
        )

        main(options)

    except KeyboardInterrupt as exc:
        import traceback
        exc_list = traceback.format_exception_only(exc)
        exc_text = "\n" + "".join(exc_list).strip("\n")
        print(exc_text)
