#!/usr/bin/env python3

# standard imports
import argparse
import os
from rich.text import Text
from rich.console import Console
import sys
import time

# Add local subnet_data module path
sys.path = [os.path.join(os.path.dirname(__file__), "python")] + sys.path

# Local imports
from constants import OWNED_SUBNETS


def _parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "-l", "--local-subtensor",
        dest="local_lite_subtensor",
        default=False,
        help="Use the specified local subtensor (i.e. la, cali, titan, etc.). "
             "When not specified, use the 'finney' network subtensor."
    )

    parser.add_argument(
        "-s", "--subnets",
        dest="netuids",
        nargs="+",
        type=int,
        help="When specified, the list of netuids are checked. When not "
             "specified, all subnets are checked."
    )

    parser.add_argument(
        "-k", "--coldkey",
        help="Specify a different coldkey to check than Rizzo. This can be either "
             "an actual coldkey address or the name of a validator who's coldkey we "
             "happen to know (i.e. rt21, yuma, kraken, tao.com, otf, muv)."
    )

    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Print verbose output."
    )

    return parser.parse_args()


def main(options):
    if options.verbose:
        bittensor.logging.enable_info()

    network = utils.get_lite_subtensor_network(options.local_lite_subtensor)

    start_time = time.time()
    subnet_data = SubnetDataMain(
        network, netuids=options.netuids, other_coldkey=options.coldkey
    )

    text = Text("\nHotkeys:")

    for netuid in subnet_data.netuids:
        validator_data = subnet_data.validator_data[netuid]
        hotkey = (
            validator_data.validator_hotkeys.Rizzo
            or (not options.coldkey and validator_data.rizzo_expected_hotkey)
            or "---"
        )
        hotkey_color = 15 if validator_data.validator_hotkeys.Rizzo else 9

        take = int(round(validator_data.rizzo_hotkey_chk_take * 100))
        if netuid in OWNED_SUBNETS:
            take_color = 9 if take > 0 else 15
        else:
            take_color = 9 if take < 9 else 15

        text.append(f"\n{netuid:3}: ")
        if not options.coldkey:
            text.append(f"{take:2}%", style=f"color({take_color})")
            text.append(" - ")
        text.append(f"{hotkey}", style=f"color({hotkey_color})")

    Console().print(text)

    total_time = round(time.time() - start_time)
    print(f"\nSubnet data gathering took {utils.get_formatted_time(total_time)}.\n")


if __name__ == "__main__":
    try:
        options = _parse_args()

        # Import bittensor and local modules after parsing args to keep the
        # bittensor module from overriding the --help arg.
        import bittensor
        from subnet_data_main import SubnetDataMain
        import utils

        main(options)

    except KeyboardInterrupt as exc:
        import traceback
        exc_list = traceback.format_exception_only(exc)
        exc_text = "\n" + "".join(exc_list).strip("\n")
        print(exc_text)
