#!/usr/bin/env python3

# standard imports
import argparse
import json
import os
from rich.console import Console
from rich.text import Text
import sys
import time

# Set path to import local modules
sys.path = [os.path.join(os.path.dirname(__file__), "python")] + sys.path

# Import local constants
from constants import (
    DEFAULT_NUM_INTERVALS_JSON,
    DEFAULT_NUM_INTERVALS_NO_JSON,
    TIMESTAMP_FILE_NAME,
)


def parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "-s", "--subnets",
        dest="netuids",
        nargs="+",
        type=int,
        help="The subnet numbers."
    )

    parser.add_argument(
        "-n", "--num-intervals",
        type=int,
        help="The number of weight setting intervals "
             f"to print out. Default: {DEFAULT_NUM_INTERVALS_JSON} when a "
             f"json folder is specified, {DEFAULT_NUM_INTERVALS_NO_JSON} "
             "when no json folder is specified."
    )

    parser.add_argument(
        "-t", "--print-tables",
        action="store_true",
        help="When specified, each subnet is printed as a table. Otherwise"
             "when not specified, everything is printed as regular text."
    )
    
    parser.add_argument(
        "-j", "--json-folder",
        help="The json cache file from which to read the data. If this is not"
             "specified then the data is gathered directly from the subtensor."
    )

    parser.add_argument(
        "-l", "--local-subtensor",
        dest="local_archive_subtensor",
        help="Use the specified local subtensor (i.e. subtensor-lite-archive). "
             "When not specified, use the 'archive' network subtensor."
    )

    parser.add_argument(
        "-k", "--coldkey",
        help="Specify a different coldkey to check than Rizzo. This can be either "
             "an actual coldkey address or the name of a validator who's coldkey we "
             "happen to know (i.e. rt21, yuma, kraken, tao.com, otf, muv)."
    )

    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Print verbose output."
    )

    options = parser.parse_args()

    if not (options.netuids or options.json_folder):
        print("ERROR: Either --subnets or --json-folder or both must be specified.")
        sys.exit(1)

    return options


def main(options):
    if options.verbose:
        bittensor.logging.enable_info()

    network = options.local_archive_subtensor or "archive"

    timestamp_msg = None
    start_time = time.time()
    if options.json_folder:
        num_intervals = options.num_intervals or DEFAULT_NUM_INTERVALS_JSON
        subnet_data = SubnetDataIntervalsFromJson(
            options.json_folder,
            netuids=options.netuids,
            num_intervals=num_intervals
        )
        timestamp_file = os.path.join(options.json_folder, TIMESTAMP_FILE_NAME)
        if os.path.isfile(timestamp_file):
            with open(timestamp_file, "r") as fd:
                timestamp = json.load(fd)["display_time"]
                timestamp_msg = Text(
                    f"Last update: {timestamp} (US Mountain Time)",
                    style=RichPrinter.get_style(0)
                )
        else:
            timestamp_msg = Text("NO TIMESTAMP FILE!", style=RichPrinter.get_style(2))
    else:
        num_intervals = options.num_intervals or DEFAULT_NUM_INTERVALS_NO_JSON
        subnet_data = SubnetDataIntervals(
            network,
            num_intervals,
            netuids=options.netuids,
            other_coldkey=options.coldkey
        )
    total_time = round(time.time() - start_time)
    print(f"\nSubnet data gathering took {utils.get_formatted_time(total_time)}.\n")

    RichPrinter(
        netuids=subnet_data.netuids,
        validator_data=subnet_data.validator_data,
        print_tables=options.print_tables,
    )

    if timestamp_msg:
        Console().print(timestamp_msg)


if __name__ == "__main__":
    try:
        options = parse_args()

        # Import bittensor and local modules after parsing args to keep the
        # bittensor module from overriding the --help arg.
        import bittensor
        from subnet_data_intervals import (
            SubnetDataIntervals,
            SubnetDataIntervalsFromJson
        )
        from subnet_printer_intervals import RichPrinter
        import utils

        main(options)

    except KeyboardInterrupt as exc:
        import traceback
        exc_list = traceback.format_exception_only(exc)
        exc_text = "\n" + "".join(exc_list).strip("\n")
        print(exc_text)
