#!/usr/bin/env python3

# standard imports
import argparse
import os
import sys
import time

# Set path to import local modules
sys.path = [os.path.join(os.path.dirname(__file__), "python")] + sys.path


def _parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "-l", "--local-subtensor",
        help="Use the specified local subtensor (i.e. la, cali, titan, etc.). "
             "When not specified, use the 'finney' network subtensor."
    )

    parser.add_argument(
        "-s", "--subnets",
        nargs="+",
        type=int,
        help="When specified, the list of netuids are checked. When not "
             "specified, all subnets are checked."
    )
    
    parser.add_argument(
        "-c", "--chk-only",
        action="store_true",
        help="When specified, only subnets in which we are child-hotkeying "
             "are displayed. When not specified, all subnets are displayed."
    )

    parser.add_argument(
        "-m", "--missing-chk",
        action="store_true",
        help="When specified, only subnets that have missing CHK are "
             "displayed. When not specified, all subnets are displayed."
    )

    parser.add_argument(
        "-k", "--coldkey",
        help="Specify a different coldkey to check than Rizzo. This can be either "
             "an actual coldkey address or the name of a validator who's coldkey we "
             "happen to know (i.e. rt21, yuma, kraken, tao.com, otf, muv)."
    )

    parser.add_argument(
        "-n", "--vali-name",
        default="Rizzo",
        help="Specify a different validator name in the table printout."
    )

    parser.add_argument(
        "-v", "--verbose",
        action="store_true",
        help="Print verbose output."
    )

    return parser.parse_args()


def main(options):
    network = utils.get_subtensor_network(options.local_subtensor)
    netuids = options.subnets or utils.get_all_subnets(network)
    sort_subnets = not bool(options.subnets)
    print_total_emission = not (options.chk_only or options.missing_chk or bool(options.subnets))

    start_time = time.time()
    validator_data = SubnetData(
        netuids, network, verbose=options.verbose, other_coldkey=options.coldkey
    ).validator_data
    subnet_data_printer = SubnetDataPrinter(
        validator_data, netuids, options.chk_only, options.missing_chk,
         sort_subnets, print_total_emission, options.vali_name
    )
    total_time = time.time() - start_time

    subnet_data_printer.print_validator_data()
    print(f"\nSubnet data gathering took {utils.format_time(round(total_time))}.\n")


if __name__ == "__main__":
    try:
        options = _parse_args()

        # Import local modules after parsing args to keep the
        # bittensor module from overriding the --help arg.
        from subnet_data_main import SubnetData
        from subnet_printer_status import SubnetDataPrinter
        import utils

        main(options)

    except KeyboardInterrupt as exc:
        import traceback
        exc_list = traceback.format_exception_only(exc)
        exc_text = "\n" + "".join(exc_list).strip("\n")
        print(exc_text)
