#!/usr/bin/env python3

# Standard imports
import argparse
import logging
import multiprocessing
import os
import sys
import time

# Add local validator_checker module path
sys.path = [os.path.dirname(__file__)] + sys.path

# local imports
from validator_checker.dereg_monitor import (
    DeregCheckerSubtensor,
    DeregCheckerJson,
)
from validator_checker.utils import (
    get_formatted_time,
    get_lite_subtensor_network,
    logger,
    SubtensorConnectionError,
)


def _parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "-i", "--interval",
        type=float,
        default=5,
        help="The number of minutes between data gathering."
    )

    subparsers = parser.add_subparsers(dest="mode")

    subtensor_parser = subparsers.add_parser(
        "from-subtensor",
        help="Gather the data directly from the subtensor."
    )

    subtensor_parser.add_argument(
        "-j", "--json-folder",
        required=True,
        help="The json folder in which to write the json files containing the data gathered "
             "by the subprocess that connects to the subtensor."
    )

    subtensor_parser.add_argument(
        "-l", "--local-subtensor",
        dest="local_lite_subtensor",
        nargs="?",
        default=False,
        help="Use the specified local subtensor (i.e. la, cali, titan, etc.). "
             "List the flag without a value to rotate between all local "
             "subtensors. When not specified, use the 'finney' network subtensor."
    )

    json_parser = subparsers.add_parser(
        "from-json",
        help="Gather the data from the json file created by the 'write_validator_data_main' process."
    )

    json_parser.add_argument(
        "-j", "--json-folder",
        required=True,
        help="The json folder containing the validator data written by the "
             "'write_validator_data_main' process."
    )

    return parser.parse_args()


def run_subtensor_check(args):
    while True:
        args.network = get_lite_subtensor_network(args.local_lite_subtensor)
        try:
            with multiprocessing.Pool(processes=1) as pool:
                pool.apply(DeregCheckerSubtensor, [args])
        except SubtensorConnectionError:
            if args.local_lite_subtensor is None:
                logger.error("Rotating subtensors and trying again.")
                time.sleep(1)
                continue
        break


def run_json_check(args):
    dereg_checker = globals().get("DEREG_CHECKER")
    if dereg_checker is None:
        dereg_checker = DeregCheckerJson(args)
        globals()["DEREG_CHECKER"] = dereg_checker
    dereg_checker.run_check()


def main():
    args = _parse_args()

    logger.setLevel(logging.INFO)

    interval_seconds = round(args.interval * 60)

    while True:
        start_time = time.time()
        if args.mode == "from-subtensor":
            run_subtensor_check(args)
        else:
            run_json_check(args)
        total_seconds = round(time.time() - start_time)

        wait_seconds = interval_seconds - total_seconds
        if wait_seconds > 0:
            wait_time_formatted = get_formatted_time(wait_seconds)
            logger.info(f"Waiting {wait_time_formatted}.")
            time.sleep(wait_seconds)
        else:
             interval_formatted = get_formatted_time(interval_seconds)
             logger.warning("Subnet deregistration check took longer than "
                            f"{interval_formatted}. Not waiting.")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt as exc:
        import traceback
        exc_list = traceback.format_exception_only(exc)
        exc_text = "\n" + "".join(exc_list).strip("\n")
        print(exc_text)
