#!/usr/bin/env python3

# standard imports
import argparse
import os
import sys

# Import local module
sys.path = [os.path.join(os.path.dirname(__file__), "python")] + sys.path


def _parse_args():
    class IntervalTimeAction(argparse.Action):
        def __call__(self, parser, namespace, values, option_string=None):
            seconds = round(values * 3600)
            setattr(namespace, self.dest, seconds)

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "-j", "--json-folder",
        required=True,
        help="The json folder in which to write the json files."
    )

    parser.add_argument(
        "-l", "--local-subtensor",
        dest="local_lite_subtensor",
        nargs="?",
        default=False,
        help="Use the specified local subtensor (i.e. la, cali, titan, etc.). "
             "List the flag without a value to rotate between all local "
             "subtensors. When not specified, use the 'finney' network subtensor."
    )

    parser.add_argument(
        "-i", "--interval",
        dest="interval_seconds",
        type=float,
        default=0,
        action=IntervalTimeAction,
        help="The number of hours between validator data gathering. If 0 or not "
             "specified then the data is gathered only once."
    )

    parser.add_argument(
        "-t", "--seconds-between-queries",
        type=int,
        default=60,
        help="The number of seconds between url queries. The higher the number, the "
             "longer it takes to query all subnets (seconds-between-queries * total subnets) "
             "but the less chance of getting rate limiting errors when querying taostats. "
             "The default is 30 seconds."
    )

    return parser.parse_args()


def run(options):
    JsonWriterPrice(options)


def main(options):
    LoopRunnerPrice(run, options)


if __name__ == "__main__":
    options = _parse_args()

    # Import bittensor and local modules after parsing args to keep the
    # bittensor module from overriding the --help arg.
    from json_writer_price import JsonWriterPrice, LoopRunnerPrice

    main(options)
