#!/usr/bin/env python3

# standard imports
import argparse
import json
import multiprocessing
import numpy
import os
import sys
import tempfile
import time

# Set path to import local modules
sys.path = [os.path.join(os.path.dirname(__file__), "python")] + sys.path

# Import local constants
from constants import (
    LOCAL_LITE_SUBTENSORS,
    DEFAULT_NUM_INTERVALS_JSON,
    LOCAL_TIMEZONE,
    DATA_FILE_NAME,
    TIMESTAMP_FILE_NAME,
)


class SubtensorConnectionError(Exception):
    pass


def _parse_args():
    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--json-main-folder",
        required=True,
        help="The json folder in which to write the main data json files."
    )

    parser.add_argument(
        "--json-intervals-folder",
        help="The json folder in which to write the intervals data json files. "
             "If not specified then intervals data will not be written."
    )

    parser.add_argument(
        "-n", "--num-weights-intervals",
        type=int,
        default=DEFAULT_NUM_INTERVALS_JSON,
        help="The number of weight setting intervals to write if --json-intervals-folder "
             f"was specified. The default is {DEFAULT_NUM_INTERVALS_JSON}."
    )

    parser.add_argument(
        "-l", "--local-subtensor",
        nargs="?",
        default=False,
        help="Use the specified local subtensor (i.e. la, cali, titan, etc.). "
             "List the flag without a value to rotate between all local "
             "subtensors. When not specified, use the 'finney' network subtensor."
    )

    parser.add_argument(
        "-c", "--chunks",
        type=int,
        default=0,
        help="The number of chunks. Each chunk will write a different json file "
             "for a range of validators."
    )

    parser.add_argument(
        "-i", "--interval",
        type=float,
        default=0,
        help="The number of minutes between validator data gathering. If 0 or not "
             "specified then the data is gathered only once."
    )

    return parser.parse_args()


def format_time(total_time):
    m = total_time/60
    minutes = int(m)
    seconds = round((m - minutes)*60)

    runtime_text = [f"{minutes} minutes"] if minutes else []
    if seconds:
        runtime_text += [f"{seconds} seconds"]
    runtime_text = ", ".join(runtime_text)

    return runtime_text


class WriteData:
    def __init__(self, options):
        self._network = options.network
        self._chunks = options.chunks
        self._num_weights_intervals = options.num_weights_intervals
        self._json_main_folder = options.json_main_folder
        self._json_intervals_folder = options.json_intervals_folder

        try:
            self._all_subnets = utils.get_all_subnets(self._network)
        except Exception as err:
            bittensor.logging.error(f"Subtensor connection failed on '{self._network}'")
            bittensor.logging.error(f"{type(err).__name__}: {err}")
            raise SubtensorConnectionError

        self._tempdir_main = tempfile.mkdtemp(prefix="write_vali_data_main_")
        if self._json_intervals_folder:
            self._tempdir_intervals = tempfile.mkdtemp(prefix="write_vali_data_intervals_")
        else:
            self._tempdir_intervals = None

        self._run()

    def _run(self):
        if self._chunks:
            for netuid_start, netuid_end in self._get_netuid_start_end_args():
                time.sleep(2)
                self._write_json_files_to_tmp(netuid_start, netuid_end)
        else:
            self._write_json_files_to_tmp()

        self._copy_tmp_to_final(self._tempdir_main, self._json_main_folder)
        if self._json_intervals_folder:
            self._copy_tmp_to_final(self._tempdir_intervals, self._json_intervals_folder)

    def _get_netuid_start_end_args(self):
        num_subnets = len(self._all_subnets)
        chunk_size = int(numpy.ceil(num_subnets / self._chunks))
        netuid_start = 0
        while True:
            netuid_end = netuid_start + chunk_size - 1
            if netuid_end >= num_subnets:
                yield netuid_start, None
                break
            yield netuid_start, netuid_end
            netuid_start = netuid_end + 1

    def _write_json_files_to_tmp(self, netuid_start=None, netuid_end=None):
        bittensor.logging.info("Gathering subnet data.")
        start_time = time.time()

        if netuid_start is not None:
            if netuid_end is not None:
                netuids = self._all_subnets[netuid_start:netuid_end+1]
            else:
                netuids = self._all_subnets[netuid_start:]
        else:
            netuids = self._all_subnets

        # TODO - Some refactoring is needed so we can get the data object
        # from SubnetDataMain and then call as_dict() to get the main data
        # and some new intervals calculation method to get the most recent
        # interval.

        # Gather subnet data
        validator_data_main = SubnetDataMain(netuids, self._network).as_dict()

        # Write main data json file
        netuid_range = f"{netuids[0]}-{netuids[-1]}"
        json_base, json_ext = os.path.splitext(DATA_FILE_NAME)
        json_file_name_main = f"{json_base}.{netuid_range}{json_ext}"
        json_file_main = os.path.join(self._tempdir_main, json_file_name_main)

        bittensor.logging.info(f"Writing main data to file: {json_file_main}")
        with open(json_file_main, "w") as fp:
            json.dump(validator_data_main, fp, indent=4)

        # If the --json-intervals-folder was specified then gather the intervals from
        # the existing json files and add interval blocks as necessary.
        if self._json_intervals_folder:
            validator_data_intervals = SubnetDataIntervalsFromMainData(
                netuids, validator_data_main, self._json_intervals_folder,
                num_intervals=self._num_weights_intervals
            ).as_dict()

            for netuid in netuids:
                json_file_name_intervals = \
                    SubnetDataIntervalsFromJson.get_json_file_name(netuid)
                json_file_intervals = os.path.join(
                    self._tempdir_intervals, json_file_name_intervals)
                bittensor.logging.info(f"Writing intervals data for netuid {netuid} to file: "
                      f"{json_file_intervals}")
                with open(json_file_intervals, "w") as fp:
                    json.dump({netuid: validator_data_intervals[netuid]}, fp, indent=4)

        total_time = time.time() - start_time
        bittensor.logging.info(f"Subnet data gathering took {format_time(round(total_time))}.")

    def _copy_tmp_to_final(self, tempdir, finaldir):
        # Remove files from final folder
        for file_name in os.listdir(finaldir):
            json_file = os.path.join(finaldir, file_name)
            if (
                not os.path.isfile(json_file)
                or os.path.splitext(json_file)[1] != ".json"
            ):
                continue
            bittensor.logging.info(f"Removing {json_file}")
            os.unlink(json_file)

        # Copy files from temp folder to final folder
        for file_name in os.listdir(tempdir):
            src_json_file = os.path.join(tempdir, file_name)
            dest_json_file = os.path.join(finaldir, file_name)
            bittensor.logging.info(f"Moving {src_json_file} to {dest_json_file}")
            os.rename(src_json_file, dest_json_file)

        # Remove temp folder
        os.rmdir(tempdir)

        # Write timestamp for final folder
        self._write_timestamp(finaldir)

    def _write_timestamp(self, json_folder):
        os.environ["TZ"] = LOCAL_TIMEZONE
        time.tzset()

        max_file_time = 0
        json_base, json_ext = os.path.splitext(DATA_FILE_NAME)
        for _file in os.listdir(json_folder):
            file_base, file_ext = os.path.splitext(_file)
            if not file_base.startswith(json_base) or file_ext != json_ext:
                continue

            json_file = os.path.join(json_folder, _file)
            file_time = os.path.getmtime(json_file)
            if file_time > max_file_time:
                max_file_time = file_time
        
        timestamp = {
            "display_time": time.ctime(max_file_time),
            "actual_time": int(max_file_time),
        }
        timestamp_file = os.path.join(json_folder, TIMESTAMP_FILE_NAME)
        bittensor.logging.info(f"Writing timestamp file: {timestamp_file}")
        with open(timestamp_file, "w") as fd:
            json.dump(timestamp, fd)


def run(options):
    WriteData(options)


def get_subtensor_network(local_subtensor, local_subtensor_index):
    if local_subtensor is False:
        return "finney"

    network_name = (
        local_subtensor or LOCAL_LITE_SUBTENSORS[local_subtensor_index]
    )
    return f"ws://subtensor-{network_name}.rizzo.network:9944"


def main(options):
    bittensor.logging.enable_info()

    os.makedirs(options.json_main_folder, exist_ok=True)
    if options.json_intervals_folder:
        os.makedirs(options.json_intervals_folder, exist_ok=True)

    local_subtensor_index = -1
    interval_seconds = round(options.interval * 60)

    while True:
        start_time = time.time()
        local_subtensor_index = (local_subtensor_index + 1) % len(LOCAL_LITE_SUBTENSORS)
        options.network = get_subtensor_network(options.local_subtensor, local_subtensor_index)

        try:
            args = [options]
            with multiprocessing.Pool(processes=1) as pool:
                pool.apply(run, args)
        except SubtensorConnectionError:
            if options.local_subtensor is None:
                bittensor.logging.error("Rotating subtensors and trying again.")
                time.sleep(1)
                continue

        # Only gather the data once.
        if not interval_seconds:
            break

        total_seconds = round(time.time() - start_time)
        wait_seconds = interval_seconds - total_seconds
        if wait_seconds > 0:
            wait_time_formatted = format_time(wait_seconds)
            bittensor.logging.info(f"Waiting {wait_time_formatted}.")
            time.sleep(wait_seconds)
        else:
            bittensor.logging.warning(
                f"Processing took {total_seconds} seconds which is longer "
                f"than {interval_seconds} seconds. Not waiting."
            )


if __name__ == "__main__":
    options = _parse_args()

    # Import bittensor and local modules after parsing args to keep the
    # bittensor module from overriding the --help arg.
    import bittensor
    from subnet_data_main import SubnetDataMain
    from subnet_data_intervals import (
        SubnetDataIntervalsFromJson,
        SubnetDataIntervalsFromMainData
    )
    import utils

    main(options)
