#!/usr/bin/env python3

# standard imports
import argparse
import os
import sys

# Set path to import local modules
sys.path = [os.path.join(os.path.dirname(__file__), "python")] + sys.path

# Import local constants
from constants import DEFAULT_NUM_INTERVALS_JSON


def _parse_args():
    class IntervalTimeAction(argparse.Action):
        def __call__(self, parser, namespace, values, option_string=None):
            seconds = round(values * 60)
            setattr(namespace, self.dest, seconds)

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--json-main-folder",
        required=True,
        help="The json folder in which to write the main data json files."
    )

    parser.add_argument(
        "--json-intervals-folder",
        help="The json folder in which to write the intervals data json files. "
             "If not specified then intervals data will not be written."
    )

    parser.add_argument(
        "-n", "--num-weights-intervals",
        type=int,
        default=DEFAULT_NUM_INTERVALS_JSON,
        help="The number of weight setting intervals to write if --json-intervals-folder "
             f"was specified. The default is {DEFAULT_NUM_INTERVALS_JSON}."
    )

    parser.add_argument(
        "-l", "--local-subtensor",
        dest="local_lite_subtensor",
        nargs="?",
        default=False,
        help="Use the specified local subtensor (i.e. la, cali, titan, etc.). "
             "List the flag without a value to rotate between all local "
             "subtensors. When not specified, use the 'finney' network subtensor."
    )

    parser.add_argument(
        "-c", "--chunk-size",
        type=int,
        default=0,
        help="The number of netuids to gather in each chunk when connecting to the subetnsor."
    )

    parser.add_argument(
        "-i", "--interval",
        dest="interval_seconds",
        type=float,
        default=0,
        action=IntervalTimeAction,
        help="The number of minutes between validator data gathering. If 0 or not "
             "specified then the data is gathered only once."
    )

    return parser.parse_args()


def run(options):
    JsonWriterMain(options)


def main(options):
    LoopRunnerMain(run, options)


if __name__ == "__main__":
    options = _parse_args()

    # Import bittensor and local modules after parsing args to keep the
    # bittensor module from overriding the --help arg.
    from json_writer_main import JsonWriterMain, LoopRunnerMain

    main(options)
