#!/usr/bin/env python3

# standard imports
import argparse
import os
import sys

# Set path to import local modules
sys.path = [os.path.join(os.path.dirname(__file__), "python")] + sys.path

# Import local constants
from constants import DEFAULT_NUM_INTERVALS_JSON


def _parse_args():
    class IntervalTimeAction(argparse.Action):
        def __call__(self, parser, namespace, values, option_string=None):
            seconds = round(values * 60)
            setattr(namespace, self.dest, seconds)

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "-j", "--json-folder",
        required=True,
        help="The json folder in which to write the json files."
    )

    parser.add_argument(
        "-n", "--num-weights-intervals",
        type=int,
        default=DEFAULT_NUM_INTERVALS_JSON,
        help="The number of weight setting intervals to write. "
             f"The default is {DEFAULT_NUM_INTERVALS_JSON}."
    )

    parser.add_argument(
        "-c", "--chunk-size",
        type=int,
        default=0,
        help="The number of netuids to gather in each chunk when connecting to the subetnsor."
    )

    parser.add_argument(
        "-i", "--interval",
        dest="interval_seconds",
        type=float,
        default=0,
        action=IntervalTimeAction,
        help="The number of minutes between validator data gathering. If 0 or not "
             "specified then the data is gathered only once."
    )
    
    parser.add_argument(
        "--local-archive-subtensor",
        help="Use the specified local archive subtensor. This requires the full "
             "ip:port or url path:port. For exmpale, specifying 'archive' "
             "won't work. You must specify 'ws://subtensor-archive.rizzo.network:9945'. "
             "When not specified, use the 'archive' network subtensor."
    )

    parser.add_argument(
        "--local-lite-subtensor",
        nargs="?",
        default=False,
        help="Use the specified local lite subtensor (i.e. la, cali, titan, etc.) for obtaining "
             "the list of subnets. List the flag without a value to rotate between all local "
             "subtensors. When not specified, use the 'finney' network subtensor."
    )

    return parser.parse_args()


def run(options):
    JsonWriterIntervals(options)


def main(options):
    LoopRunnerIntervals(run, options)


if __name__ == "__main__":
    options = _parse_args()

    # Import bittensor and local modules after parsing args to keep the
    # bittensor module from overriding the --help arg.
    from json_writer_intervals import JsonWriterIntervals, LoopRunnerIntervals

    main(options)
