VTRUST_ERROR_THRESHOLD = 0.2
VTRUST_WARNING_THRESHOLD = 0.1
UPDATED_ERROR_THRESHOLD = 1080  # 3x normal subnet tempo (360 blocks)
UPDATED_WARNING_THRESHOLD = 720  # 2x normal subnet tempo (360 blocks)